#!../bash
#$Id: run-set-x,v 1.1.1.1 2012/12/02 15:24:52 wb8tyw Exp $

TEST_NAME='set-x'
TEST_FILE="/tmp/${TEST_NAME}.check"
${THIS_SH} ./${TEST_NAME}.tests > $TEST_FILE 2>&1 < /dev/null
set -f
diff $TEST_FILE ${TEST_NAME}.right && rm -f $TEST_FILE

# Return code tells testing mechanism whether passed or not.
exit $?
