/* File: vms_main_wrapper.c
 *
 * $Id: vms_main_wrapper.c,v 1.2 2013/06/09 17:07:00 wb8tyw Exp $
 *
 * This module provides a wrapper around the main() function of a ported
 * program for two functions:
 *
 * 1. Make sure that the argv[0] string is set as close as possible to
 *    what the original command was given.
 *
 * 2. Make sure that the posix exit is called.
 *
 * Copyright 2012, John Malmberg
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT
 * OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 *
 */


#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <stdlib.h>

#define __NEW_STARLET 1

#include <descrip.h>
#include <dvidef.h>
#include <efndef.h>
#include <fscndef.h>
#include <iledef.h>
#include <iosbdef.h>
#include <stsdef.h>
#include <starlet.h>

void *MemoryAllocations[2]={NULL,NULL};

void DeallocMainWrapperMemory()
   {
   for (int i=0; (i < sizeof(MemoryAllocations)/sizeof(void *)); i++)
      if (MemoryAllocations[i] != NULL) free(MemoryAllocations[i]);
   }
/*
When the DECC$POSIX_COMPLIANT_PATHNAMES feature is enabled, the HOME environment
variable can be initialized by the CRTL with an OpenVMS formatted path instead
of the expected UNIX formatted path. This routine forces the value for the HOME
environment variable to be UNIX formatted if it is not already.
*/
void force_env_home_to_unix_format(char **env)
   {
   unsigned int FoundHome=0;
   char *HomeEntry;
   char * HomeVal;

   for (unsigned int Index = 0; ((env[Index] != NULL) && !FoundHome); Index++)
      {
      if ((HomeEntry = strstr(env[Index], "HOME=")) != NULL)
         {
         FoundHome = 1;
         HomeVal = HomeEntry + 5;
         if (strchr(HomeVal,':') != NULL)
            {
            strcpy(HomeVal,decc$translate_vms(HomeVal));
            }
         }
      }
   }
int original_main(int argc, char ** argv, char **env);

int main(int argc, char ** argv, char **env) {
int status;
int result;
char arg_nam[256];
char **new_argv;
char *cpos;
char *one_cmd_arg=NULL;
char * dotexe;
int in_opts;
int do_one_cmd=0;
int arg_len;
int new_arg_size;
int exit_value;

#ifdef TEST_MAIN
    printf("original argv[0] = %s\n", argv[0]);
#endif

    new_argv = argv;
    result = 0;

    /* If the path name starts with a /, then it is an absolute path	     */
    /* that may have been generated by the CRTL instead of the command name  */
    /* If it is the device name between the slashes, then this was likely    */
    /* from the run command and needs to be fixed up.			     */
    /* If the DECC$POSIX_COMPLIANT_PATHNAMES is set to 2, then it is the     */
    /* DISK$VOLUME that will be present, and it will still need to be fixed. */
    if (argv[0][0] == '/') {
	char * nextslash;
	int length;
	struct _ile3 itemlist[3];
	struct _iosb dvi_iosb;
	char alldevnam[64];
	unsigned short alldevnam_len;
	struct dsc$descriptor_s devname_dsc;
	char diskvolnam[256];
	unsigned short diskvolnam_len;

	  /* Get some information about the disk */
	/*--------------------------------------*/
	itemlist[0].ile3$w_length = (sizeof alldevnam) - 1;
	itemlist[0].ile3$w_code = DVI$_ALLDEVNAM;
	itemlist[0].ile3$ps_bufaddr = alldevnam;
	itemlist[0].ile3$ps_retlen_addr = &alldevnam_len;
	itemlist[1].ile3$w_length = (sizeof diskvolnam) - 1 - 5;
	itemlist[1].ile3$w_code = DVI$_VOLNAM;
	itemlist[1].ile3$ps_bufaddr = &diskvolnam[5];
	itemlist[1].ile3$ps_retlen_addr = &diskvolnam_len;
	itemlist[2].ile3$w_length = 0;
	itemlist[2].ile3$w_code = 0;

	/* Add the prefix for the volume name. */
	/* SYS$GETDVI will append the volume name to this */
	strcpy(diskvolnam,"DISK$");

	nextslash = strchr(&argv[0][1], '/');
	if (nextslash != NULL) {
	    length = nextslash - argv[0] - 1;

	    /* Cast needed for HP C compiler diagnostic */
	    devname_dsc.dsc$a_pointer = (char *)&argv[0][1];
	    devname_dsc.dsc$w_length = length;
	    devname_dsc.dsc$b_dtype = DSC$K_DTYPE_T;
	    devname_dsc.dsc$b_class = DSC$K_CLASS_S;

	    status = SYS$GETDVIW
	       (EFN$C_ENF,
		0,
		&devname_dsc,
		itemlist,
		&dvi_iosb,
		NULL, 0, 0);
	    if (!$VMS_STATUS_SUCCESS(status)) {
		/* If the sys$getdviw fails, then this path was passed by */
		/* An exec() program and not from DCL, so do nothing */
		/* An example is "/tmp/program" where tmp: does not exist */
#ifdef TEST_MAIN
		printf("sys$getdviw failed with status %d\n", status);
#endif
		result = 0;
	    } else if (!$VMS_STATUS_SUCCESS(dvi_iosb.iosb$w_status)) {
#ifdef TEST_MAIN
		printf("sys$getdviw failed with iosb %d\n", dvi_iosb.iosb$w_status);
#endif
		result = 0;
	    } else {
		char * devnam;
		int devnam_len;
		char argv_dev[64];

		/* Null terminate the returned alldevnam */
		alldevnam[alldevnam_len] = 0;
		devnam = alldevnam;
		devnam_len = alldevnam_len;

		/* Need to skip past any leading underscore */
		if (devnam[0] == '_') {
		    devnam++;
		    devnam_len--;
		}

		/* And remove the trailing colon */
		if (devnam[devnam_len - 1] == ':') {
		    devnam_len--;
		    devnam[devnam_len] = 0;
		}

		/* Null terminate the returned volnam */
		diskvolnam_len += 5;
		diskvolnam[diskvolnam_len] = 0;

		/* Check first for normal CRTL behavior */
		if (devnam_len == length) {
		    strncpy(arg_nam, &argv[0][1], length);
		    arg_nam[length] = 0;
		    result = (strcasecmp(devnam, arg_nam) == 0);
		}

		/* If we have not got a match check for POSIX Compliant */
		/* behavior.  To be more accurate, we could also check */
		/* to see if that feature is active. */
		if ((result == 0) && (diskvolnam_len == length)) {
		    strncpy(arg_nam, &argv[0][1], length);
		    arg_nam[length] = 0;
		    result = (strcasecmp(diskvolnam, arg_nam) == 0);
		}
	    }
	}
    } else {
	/* The path did not start with a slash, so it could be VMS format */
	/* If it is vms format, it has a volume/device in it as it must   */
	/* be an absolute path */
	struct dsc$descriptor_s path_desc;
	int status;
	unsigned int field_flags;
	struct _ile2 item_list[5];
	char * volume;
	char * name;
	int name_len;
	char * ext;

	path_desc.dsc$a_pointer = (char *)argv[0]; /* cast ok */
	path_desc.dsc$w_length = strlen(argv[0]);
	path_desc.dsc$b_dtype = DSC$K_DTYPE_T;
	path_desc.dsc$b_class = DSC$K_CLASS_S;

	/* Don't actually need to initialize anything buf itmcode */
	/* I just do not like uninitialized input values */

	/* Sanity check, this must be the same length as input */
	item_list[0].ile2$w_code = FSCN$_FILESPEC;
	item_list[0].ile2$w_length = 0;
	item_list[0].ile2$ps_bufaddr = NULL;

	/* If the device is present, then it if a VMS spec */
	item_list[1].ile2$w_code = FSCN$_DEVICE;
	item_list[1].ile2$w_length = 0;
	item_list[1].ile2$ps_bufaddr = NULL;

	/* we need the program name and type */
	item_list[2].ile2$w_code = FSCN$_NAME;
	item_list[2].ile2$w_length = 0;
	item_list[2].ile2$ps_bufaddr = NULL;

	item_list[3].ile2$w_code = FSCN$_TYPE;
	item_list[3].ile2$w_length = 0;
	item_list[3].ile2$ps_bufaddr = NULL;

	/* End the list */
	item_list[4].ile2$w_code = 0;
	item_list[4].ile2$w_length = 0;
	item_list[4].ile2$ps_bufaddr = NULL;

	status = SYS$FILESCAN(&path_desc, item_list, &field_flags, NULL, NULL);

	if ($VMS_STATUS_SUCCESS(status) &&
	   (item_list[0].ile2$w_length == path_desc.dsc$w_length) &&
	   (item_list[1].ile2$w_length != 0)) {

	    char * dollar;
	    int keep_ext;
	    int i;

	    /* We need the filescan to be successful, */
	    /* same length as input, and a volume to be present */

	    /* Need a new argv array */
	    new_argv = malloc((argc + 1) * (sizeof(char *)));
	    new_argv[0] = arg_nam;
	    i = 1;
	    while (i < argc) {
		new_argv[i] = argv[i];
		i++;
	    }

	    /* We will assume that we only get to this path on a version */
	    /* of VMS that does not support the EFS character set */

	    /* There may be a xxx$ prefix on the image name.  Linux */
	    /* programs do not handle that well, so strip the prefix */
	    name = item_list[2].ile2$ps_bufaddr;
	    name_len = item_list[2].ile2$w_length;
	    dollar = strrchr(name, '$');
	    if (dollar != NULL) {
		dollar++;
		name_len = name_len - (dollar - name);
		name = dollar;
	    }

	    strncpy(arg_nam, name, name_len);
	    arg_nam[name_len] = 0;

	    /* We only keep the extension if it is not ".exe" */
	    keep_ext = 0;
	    ext = item_list[3].ile2$ps_bufaddr;

	    if (item_list[3].ile2$w_length != 1) {
		if (item_list[3].ile2$w_length != 4) {
		    keep_ext = 1;
		} else {
		    int x;
		    x = strncmp(ext, ".exe", 4);
		    if (x != 0) {
			keep_ext = 1;
		    }
		}
	    }

	    if (keep_ext == 1) {
		strncpy(&arg_nam[name_len], ext, item_list[3].ile2$w_length);
	    }
	}
    }

    /* Check if argv[0] ends in . or .exe on the name (case insenstive) and truncate */
    /* it if it does. */
    dotexe = strrchr(argv[0], '.');
    if (dotexe != NULL)
       {
       if ((dotexe[1] == '\0') || ((dotexe[1] == 'e' || dotexe[1] == 'E') &&
           (dotexe[2] == 'x' || dotexe[2] == 'X') &&
           (dotexe[3] == 'e' || dotexe[3] == 'E') &&
           (dotexe[4] == '\0')))
          {
          *dotexe = '\0';
          }
       }

    if (result) {
	char * lastslash;
	char * dollar;
	char * lastdot;
	char * extension;

	/* This means it is probably the name from a DCL command */
	/* Find the last slash which separates the file from the */
	/* path. */
	lastslash = strrchr(argv[0], '/');

	if (lastslash != NULL) {
	    int i;

	    lastslash++;

	    /* There may be a xxx$ prefix on the image name.  Linux */
	    /* programs do not handle that well, so strip the prefix */
	    dollar = strrchr(lastslash, '$');

	    if (dollar != NULL) {
		dollar++;
		lastslash = dollar;
	    }

	    strcpy(arg_nam, lastslash);

	    /* In UNIX mode + EFS character set, there should not be a */
	    /* version present, as it is not possible when parsing to  */
	    /* tell if it is a version or part of the UNIX filename as */
	    /* UNIX programs use numeric extensions for many reasons.  */

	    lastdot = strrchr(arg_nam, '.');
	    if (lastdot != NULL) {
		int i;

		i = 1;
		while (isdigit(lastdot[i])) {
		    i++;
		}
		if (lastdot[i] == 0) {
		    *lastdot = 0;
		}
	    }

                    if (argc > 2)
                       {
                       in_opts=1;
                       do_one_cmd = 1;
	       new_arg_size = 0;
	       for (i=1; ((i < argc) && do_one_cmd); i++)
	          {
	          arg_len = strlen(argv[i]);
	          /* Check if we are still in the midst of command options. */
	          if (argv[i][0] != '-') in_opts = 0;
	          if  (in_opts && (arg_len == 2) && (strcmp(argv[i], "-c") == 0)) do_one_cmd = 0;
	          new_arg_size += arg_len + 1;
	          } 
	       }

                    if (do_one_cmd)
                       {
                       new_argv = malloc(4 * sizeof(char *));
                       new_argv[0] = arg_nam;
                       new_argv[1] = "-c";
                       one_cmd_arg = malloc (new_arg_size);
                       *one_cmd_arg = '\0';
                       cpos = one_cmd_arg;
                       for (i=1; (i < argc); i++)
                          {
                          arg_len = strlen(argv[i]);
                          strcpy(cpos, argv[i]);
                          cpos += arg_len;
                          *cpos = ' ';
                          cpos++;
                          }
                       one_cmd_arg[new_arg_size - 1] = '\0';
                       new_argv[2] = one_cmd_arg;
                       new_argv[3] = NULL;
                       argc = 3;
                       }
                    else
                       {                
	       /* Need a new argv array */
	       new_argv = malloc((argc + 1) * (sizeof(char *)));
	       new_argv[0] = arg_nam;
	       i = 1;
	       while (i < argc) {
		new_argv[i] = argv[i];
		i++;
	          }
	       new_argv[i] = 0;
                       }
       } 
    else
       {
       /* There is no way that the code should ever get here */
       /* As we already verified that the '/' was present */
       fprintf(stderr, "Sanity failure somewhere we lost a '/'\n");
       }
    }
    
    if (new_argv != argv)
       {
       MemoryAllocations[0] = (void *)new_argv;
       MemoryAllocations[1] = (void *)one_cmd_arg;
       if (atexit(DeallocMainWrapperMemory))
          printf("WARNING: Unable to register function to deallocate "
                 "memory for main() wrapper arguments array!\r\n");
       }
    force_env_home_to_unix_format(env);
    exit(original_main(argc, new_argv, env));
}

#define main original_main

#ifdef TEST_MAIN

int main(int argc, char ** argv, char **env) {

    printf("modified argv[0] = %s\n", argv[0]);

    return 0;
}

#endif
